# Generated by Django 3.1.1 on 2020-11-22 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('german', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='topic',
        ),
        migrations.AlterField(
            model_name='blog',
            name='created_by',
            field=models.CharField(choices=[('Ranjith', 'Ranjith'), ('Rinee', 'Rinee')], max_length=32),
        ),
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
